---
- name: ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
    state: installed

- name: add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins.deb"
  when: jenkins_version is defined

- name: check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins.deb"
  register: specific_version

- name: install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins.deb"
    state: installed
  when: specific_version.stat.exists
  notify: configure default users

- name: validate Jenkins is installed and register package name.
  apt:
    name: jenkins
    state: present
  notify: configure default users

- name: install Jenkins from repository.
  apt:
    name: jenkins
    state: installed
  when: jenkins_version is undefined
