- name: Add Java 8 repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Agree to oracle license
  become: yes
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

- name: Install Java 8
  become: yes
  apt: name=oracle-java8-installer force=yes

- name: Tomcat8 Installation By using zip file
  get_url:  url=http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.tar.gz dest=/home/ubuntu/ owner=ubuntu group=ubuntu

- name: Un-Archive zip file
  unarchive: src=/home/ubuntu/apache-tomcat-8.5.11.tar.gz dest=/home/ubuntu/ copy=no

- name: change permissions file
  file: path=/home/ubuntu/apache-tomcat-8.5.11 owner=ubuntu group=ubuntu recurse=yes

- name: service tomcat start
  command: chdir=/home/ubuntu/apache-tomcat-8.5.11/bin ./startup.sh
